my:
  text: "hello; **** This is ALL MS Development Environment *****"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6560/eureka
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql_maindb1
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.generate_statistics: false
my:
  text: "hello; **** This is ALL MS Development Environment *****"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6560/eureka
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql_maindb1
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.generate_statistics: false
  
otlp: #این بخش نقطه انتهایی OpenTelemetry Collector را که متریک ها و ردیابی ها به آن صادر می شوند مشخص می کند.
   metrics:
   export:
     url: http://localhost:4318/v1/metrics
     step: 10s
   tracing:
     endpoint: http://localhost:4318/v1/traces
     export:
        step: 10s
     sampling:
      probability: 1.0	
